stages:
  data_preprocessing:
    cmd: python3 src/data_preprocessing.py
    deps:
    - src/data_preprocessing.py
  train:
    cmd: python3 src/train.py
    deps:
    - src/train.py
    params:
    - train
    outs:
    - models
  evaluate:
    cmd: python3 src/evaluation.py
    deps:
    - src/evaluation.py
    - models/
    metrics:
    - datasets/data/evaluation/metrics.json
    plots:
    - datasets/data/evaluation/plots/confusion_matrix.png
